######################################################################
# Automatically generated by qmake (2.01a) Thu May 6 23:48:36 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h puzzleboard.h
SOURCES += main.cpp mainwindow.cpp puzzleboard.cpp
RESOURCES += mainwindow.qrc
